### PR TITLE
Code clean

### PR DESCRIPTION
**Pull request by MarkAHQ**
I refactored most of the project to follow clean coding principles. You might want to review the code one commit at a time to see how I worked my way up to where I was - or, I suppose, you could just review the end result if you're comfortable with that high-level review. You won't be able to tell if I broke anything very easily, that way though :)

I had heard that you specifically built this project to NOT be OOP, but I originally was going to refactor to use interfaces and polymorphism. In the end I decided it was better without.

With the heavy use of static code it was more of a re-organisation of the code than a re-write. I mostly moved code around, and broke it up for readability and where I could simplified the logic and handed over some of the error processing to built-in systems.

The biggest change was to use Microsoft's CommandLine library instead of manually parsing and handling the commands. This library is still in beta. I don't know why they didn't introduce it decades ago, tbh.

My last point is I was mostly doing this for fun and practice. I'd prefer, if we're going to share this around the practice, to give people some good direction in terms of patterns and organisation.

### CODE REVIEW

**Comment by c-schembri** [comment]
`I had heard that you specifically built this project to NOT be OOP, but I originally was going to refactor to use interfaces and polymorphism. In the end I decided it was better without.`

That's true. You already know my reasons why so I won't repeat them again--but I wanted to demonstrate what a non-OOP program would look like at its core to other members of the automation team (despite how tedious it is writing `static` over and over again).

`With the heavy use of static code it was more of a re-organisation of the code than a re-write. I mostly moved code around, and broke it up for readability and where I could simplified the logic and handed over some of the error processing to built-in systems.`

`The biggest change was to use Microsoft's CommandLine library instead of manually parsing and handling the commands. This library is still in beta. I don't know why they didn't introduce it decades ago, tbh.`

I have heard of this library but never bothered because it wasn't even in preview when I last looked at it. 
Obviously, the program before these changes was fairly basic in structure, so I do think the structure needed to be updated.

`My last point is I was mostly doing this for fun and practice. I'd prefer, if we're going to share this around the practice, to give people some good direction in terms of patterns and organisation.`
Of course that's something good to do, and I intended the same. I just didn't want it to be another stock-standard OOP demonstration for C# which can be found all over the internet and is taught in most universities.

Things like polymorphism and inheritance start to make more sense when you ship a library and want to grant the user the ability to change implementation details to fit their use-cases. For a standard one-job program, I don't see the point however. Perhaps we can make another solution where we define all these interfacing details and the end-user/student/whatever is required to implement the details?

I'll make another comment shortly commenting on the details of the commits you've applied.

**Comment by c-schembri** [comment]
I went through each commit and each file and had a look at what you did. Instead of adding the comments to the commit message, and because the program is small enough to do so, I'll write a quick review on each file I have made changes to, on the back of your changes--and you can see the diffs in the relevant files to see what I'm talking about.

`Program.cs`
If we pass an invalid command to the command library, it will return early in a failed state. However, the `finally` will try to call `TearDownDriver` despite the application needing to already exit. Instead of a `try-finally` I added a check to ensure that we only teardown if a valid command was first passed.


`Commands.cs`
We can leverage static ctors to guarantee that the Commands are initialised without having to constantly check if the Commands are null at run-time. Also, I don't think it's the best to have constant strings unless we need to re-use them, which we don't in this case. Finally, it's standard practice to have CLI args be prefixed with `--` so I added that to the `commit` command.

`DriverManager.cs`
Like above, instead of making the responsibility belong to calling code--we already know that we _always_ need to setup the driver before it can be used. Therefore we can leverage a static ctor to guarantee that anytime `Driver` is called, it will be setup (without having to rely on an initial `SetUpDriver` call. I've also moved the `Driver` to this file instead of `Program` because it makes no sense to sit at level anymore.

`TimesheetPage.cs`
`DoYourTimesheet` does not need to return anything.
In `SetTimesheetEntries` and `ProcessWeek` you passed a `ref int` though I'm not sure why; we can simply have `ProcessWeek` return the number of hours processed to calling code.

**Comment by MarkAHQ** [comment]
> I went through each commit and each file and had a look at what you did. Instead of adding the comments to the commit message, and because the program is small enough to do so, I'll write a quick review on each file I have made changes to, on the back of your changes--and you can see the diffs in the relevant files to see what I'm talking about.
> 
> `Program.cs` If we pass an invalid command to the command library, it will return early in a failed state. However, the `finally` will try to call `TearDownDriver` despite the application needing to already exit. Instead of a `try-finally` I added a check to ensure that we only teardown if a valid command was first passed.

The CommandLine library, I thought, handled an invalid command gracefully. So. originally I had a nice simple:
```
cmd.Invoke(args);
Driver.Quit();
```
Since that didn't always work (such as if you enter an invalid command) - plus exceptions could short-circuit us - I changed it to:
```
try
{
  cmd.Invoke(args);
}
finally
{
  Driver.Quit();
}
```
I think this needs a bit more thought. I've got a couple test cases:

Invalid Command - exit before DriverManager called
1. execute: TimesheetTimothy.exe --custard
2. Expect: System.CommandLine's "invalid command" handling, and no browser opening

Happy Path
1. execute: TimesheetTimothy.exe --commit <username>
2. enter password correctly
3. encounter no exceptions
4. Expect: "Timothy would have commited your timesheet in [arg] milliseconds", and driver shut down

Exception thrown after DriverManager called
1. execute: TimesheetTimothy.exe --commit <username>
2. enter password INCORRECTLY
3. Expect: "Entered username or password is incorrect", preferrably with no exception spam, browser is closed, and chromedriver is shut down


I don't think either of our solutions are passing all those tests, yet. The closest I got was I had it going with my original solution, but the first test failed because the browser briefly opened.

> 
> `Commands.cs` We can leverage static ctors to guarantee that the Commands are initialised without having to constantly check if the Commands are null at run-time. Also, I don't think it's the best to have constant strings unless we need to re-use them, which we don't in this case. Finally, it's standard practice to have CLI args be prefixed with `--` so I added that to the `commit` command.

*ctors*: Good idea. I was playing with that for a while - ran into a garbage collection issue blowing away my arguments. Decided to do a singleton pattern. I like your idea better. Not a huge fan of singletons as a rule.
*constants*: I can't remember what you originally had. I changed the filename from a .txt to a .json so there was at least one time it changed! Having said that, what you've done by making it a parameter is to make it even MORE changeable. I think this is better. Now we could have, for example, an optional parameter where you tell Timothy the jobs.json file. Then a user can have several that they typically use ("my usual one", "the one with a PH on mondays", "the one I use over xmas break") and passes in a parameter to choose a different file than jobs.json, if they want.
*CLI args*: The way you had the program originally it read as "<Program> <command> <argument>". Commands could have Sub-Commands, and Options is another thing you can pass in. For example, the command “dotnet add package” has “dotnet” as the root command, “add” as a subcommand and “package” as the subcommand to add. Options are, well, optionally. Arguments are values you need to pass to a command or option. With "dotnet new", the "--name" option has an argument for specifying the name of the project. e.g. `dotnet new --name "projectname"`. 
  So back to naming conventions: commands don't typically use `--`, options do. And arguments usually don't either, because they're values (often they're wrapped in double-quotes, but that's only required with spaces and such.) I figured in the future you might introduce new commands, with different (optional) options and parameters, etc. `TimesheetTimothy draft mark.arnold@accesshq.com --jobs "xmas break.json"` `TimesheetTimothy submit mark.arnold@accesshq.com --date 23/12/2022`
> 
> `DriverManager.cs` Like above, instead of making the responsibility belong to calling code--we already know that we _always_ need to setup the driver before it can be used. Therefore we can leverage a static ctor to guarantee that anytime `Driver` is called, it will be setup (without having to rely on an initial `SetUpDriver` call. I've also moved the `Driver` to this file instead of `Program` because it makes no sense to sit at level anymore.

This one gets a bit tricky. You had to undo passing the ChromeConfig to the constructor which is a shame. I suppose that future requirement could be handled by a factory and a run-time parameter... which is basically what I was thinking when I made it a parameter to pass into SetUpDriver, but I thought it was clearer in the calling code: "I am setting up a driver, and it is a chromedriver. If you want another type of driver, you just have to change this parameter." Your new method here hides all that. "Don't worry your pretty head, you have a Driver. If you want to change it, you need to dig in a bit and realise that it's handled lower-down." Pros and cons. It's just an exercise anyway - as if anyone would want to use anything but Chrome. (Having said that, it's not that unlikely that in the future this is has wide-spread use among the team, and some of them may not use Chrome - they might prefer Firefox, or their client doesn't allow Chrome or something.)

> 
> `TimesheetPage.cs` `DoYourTimesheet` does not need to return anything. In `SetTimesheetEntries` and `ProcessWeek` you passed a `ref int` though I'm not sure why; we can simply have `ProcessWeek` return the number of hours processed to calling code.

I wasn't 100% sure if we were still using the return code. I didn't like the idea, so I hoped I got rid of it, but left it. I shouldn't have - should have worked out if it was needed or not. (One of the reasons I don't like return codes. Very vague what they do.)

I didn't want ProcessWeek to return because I didn't think it made logical sense. It processes the week. If it returns something, it really *needs* to be called "GetTotalHours" ... but that's not what it does, it processes the week of entries. So if I was coming in fresh, I'd be confused either way. If it's called GetTotalHours, but then goes and fills in a whole timesheet, I'd definitely be thinking "what in the fuck???" ... if we call it ProcessWeek, but it returns an int, I'd be thinking "what the hell does it actually return?" and I'd need to read the code from top to bottom to determine that.

Having said all that, I think doing a sanity check on the total hours makes a lot of sense. I was originally going with a lamba to pass in the for-logic so it read as "Process the week of entries, and use this daily processing logic" but it was getting unnecessarily complex. I decided to use the ref so the naming stays pure, and we can track the total hours as a little ride-along. Now it reads as "Process this week you've passed in, and btw I need an int to track the total hours with." `ProcessWeek(Week week, ref int totalHours)`

*Ultimately* this stems from breaking the Single-Responsibility rule. That method is doing 2 things: Processing the week of entries, and counting the total hours. But I couldn't think of a way of refactoring to split those 2 jobs up without having to do a lot of extra Selenium steps (i.e. counting the hours or grabbing the total from the webpage after the fact.) And interacting with webpages is slow... My thinking here was that it only *just* breaks the SR rule because it still primarily processes the week. It's kind of the calling code's responsibility to manage the total hours by attaching them to the method. Hence the very explicity "this is a ref variable!"

> 
> Lastly, I noticed your use of jump tables instead of switch expressions. I don't mind either way (switches/switch expressions are lowered into jump tables by the compiler where possible as far as I know), but I'd like to know your reasoning why for this change.

Personal preference mostly. I don't like switches. It was these switch statements I was going to turn into polymorphic objects. "ifs and switches are just a poor man's polymorphism." The final code was going to look like:

```
internal string GetResultMessage(IExitMessage message)
{
  return message.ConstructString();
}
```

The calling code, using a Dictionary look-up would look like:
```
GetResultMessage(messagesLookup[code]);
```
because `messageLookup` would be defined as: `Dictionary<ExitCode, IExitMessage>` ... which leads me back to, I still need a dictionary or something to map codes to objects.

I considered it, just as a demonstration, but I figured if other engineers looked at this, they'd think it was just "the way to do things" even though, in this case, it would be total overkill. So I was afraid they'd end up with polymorphism as a hammer, and everything as a nail.

So... I short-circuited it. I don't like switch statements, but the real reason for me was the logic on these really boils down to it being a mapping between a code and a string. By leaving it as a switch statement it leaves the door open for some "bonus" logic, which starts to break the SR rule and could catch people out if they don't realise it's doing some magic behind the scenes.

By making it a dictionary, particularly one called MessagesLookup (huh, did I not call it that in the end?) it communicates "All you do is pass in a code, and you get a message, just like any old array."

Also, it makes it more concise, I think.

Of course, it's a Func, so there's a lot of magic you could sneak in if you wanted but I think it communicates the "lookup table" intent better. I really just wanted a `Dictionary<string, string>` but I also liked the "arg" idea, so merged them together into what I did.

In the end, I thought the `Dictionary<string Func<string, string>>` came out pretty well. The calling code is to the point, and the "table" looks like a simple-to-extend table of Codes mapping to Strings.

**Comment by MarkAHQ** [comment]
Looks like your latest change might have fixed the first point I was testing this arvo :)

I'd suggest reading my epic comment, make any final tweaks if you want, and merge 'er in

**Comment by c-schembri** [comment]
`So back to naming conventions: commands don't typically use --, options do. And arguments usually don't either, because they're values (often they're wrapped in double-quotes, but that's only required with spaces and such.) I figured in the future you might introduce new commands, with different (optional) options and parameters, etc. TimesheetTimothy draft mark.arnold@accesshq.com --jobs "xmas break.json" TimesheetTimothy submit mark.arnold@accesshq.com --date 23/12/2022`

Yeah you're right. But actually I think it's inconsistent across platforms and applications (what else is new?). By commands I did mean options, so `TimesheetTimothy` would be the application and `commit` would be the option/arg. Regardless, it's stylisation at this point. And it seems Microsoft is stepping away from the `--` prefix altogether:

> Starting with .NET SDK 7.0.100 Preview 2, the dotnet new syntax has changed:

    The --list, --search, --install, and --uninstall options became list, search, install and uninstall subcommands.
    
 Though because we're on Windows I'll revert it to `commit`.

`Your new method here hides all that. "Don't worry your pretty head, you have a Driver. If you want to change it, you need to dig in a bit and realise that it's handled lower-down." Pros and cons. It's just an exercise anyway - as if anyone would want to use anything but Chrome. (Having said that, it's not that unlikely that in the future this is has wide-spread use among the team, and some of them may not use Chrome - they might prefer Firefox, or their client doesn't allow Chrome or something.)`

Yeah I thought about this issue. What I don't understand is: _where_ does one determine to use another, e.g., Firefox or Chrome? I imagine it would be at the most initial point, e.g., through the CLI, an environment file, etc. But if it is that way, then we can simply add code to check for that argument/environment variable in the DriverManager code instead of the code that consumes the DriverManager.

`I didn't want ProcessWeek to return because I didn't think it made logical sense. It processes the week. If it returns something, it really needs to be called "GetTotalHours" ... but that's not what it does, it processes the week of entries. So if I was coming in fresh, I'd be confused either way. If it's called GetTotalHours, but then goes and fills in a whole timesheet, I'd definitely be thinking "what in the fuck???" ... if we call it ProcessWeek, but it returns an int, I'd be thinking "what the hell does it actually return?" and I'd need to read the code from top to bottom to determine that.

Having said all that, I think doing a sanity check on the total hours makes a lot of sense. I was originally going with a lamba to pass in the for-logic so it read as "Process the week of entries, and use this daily processing logic" but it was getting unnecessarily complex. I decided to use the ref so the naming stays pure, and we can track the total hours as a little ride-along. Now it reads as "Process this week you've passed in, and btw I need an int to track the total hours with." ProcessWeek(Week week, ref int totalHours)`

Would an `out` parameter be a more suitable option? E.g.,
`ProcessWeek(Week week, out int totalHours)`
That way calling code does _not need_ to pass a ref, we get the total hours with minimal effort, and we understand the total hours as a side-effect of processing the week instead of thinking it's the purpose of the function.

**Comment by MarkAHQ** [comment]
> e.g., through the CLI, an environment file, etc. But if it is that way, then we can simply add code to check for that argument/environment variable in the DriverManager code instead of the code that consumes the DriverManager.

That would be the way to do it. That's kinda what I meant when I said "I suppose that future requirement could be handled by a factory and a run-time parameter". I think either location is fine, it really is only a question of design. If we might have quite different scenarios/code paths that utilise different browsers, we might want to make it clear. For example, I could imagine a future where we sometimes force a chromedriver `SetupDriver(new ChromeOptions());` or send it to the factory `SetupDriver(DriverFactory.GetDriver());` etc.

I think it's more likely it's just a preference flag that a user might switch, so for a code maintainer, we probably want to hide that information away (so burying it into the DriverManager like you have done.)

Since we aren't sure of the future, we should err on the side of whatever is the most flexible - what leaves us more open for future changes? To that end, I think either is fine although putting it in the calling code does make it a little clearer, but that might be just my opinion. I see `SetupDriver()` and my first thought is: "What type? How? Is it now global - because it doesn't return anything..." if I see `SetupDriver(someChromeThing);` then I'm thinking: Ok, this clearly sets up a chrome driver. Probably called "Driver" or "ChromeDriver". If I see `SetupDriver(DriverFactory.GetDriver());` then I know that it definitely sets up a driver, but what type is handled by a run-time parameter of some sort (CLI, or setting file, or something.)

btw: You could easily build a factory that does nothing, just for future. Just have DriverFactory.GetDriver() always return ChromeOptions, and have SetupDriver take an IOptions. In the future, if we want, we can change the implementation to return different driver options based on flags. But we don't have to do anything with it yet. We just design it for the future, and it's almost like a todo without the comment. "Hey a factory pattern... that does nothing. Ok, I guess the plan is to expand on it in the future." This assumes you know what a factory pattern is, of course. An inexperienced engineer might look at the factory code and think that is all there is to it and wonder why it is there. Anyway, just a tangent. Leave it as-is.

I think I would have gone with `Driver = SetupDriver(DriverFactory.GetDriver());` myself, but that's probably just me. I'd expect a method that creates a driver and hands it back, then I manage it from there. I can see the logic of hiding it away and just making it magic in this case. The reason why I'd expect that, and why it's just my experience that causes me to expect that, is because normally with test cases we want to leave the door open for parallel execution. Static Drivers, in particular, make that hard-to-impossible, so normally we manage them in the calling code.

*However*: I can't think of a scenario where you'd *want* parallel execution of this program, and furthermore more modern approaches to parallel execution would prefer infrastructure provisioning (i.e. horizonal scaling) instead of multi-threaded parallel execution. If you can isolate with your infrastructure, you can get away with static stuff just fine. I recommend against it mostly because it takes away that option which you might want in the future.


> 
> > I didn't want ProcessWeek to return because I didn't think it made logical sense. It processes the week. If it returns something, it really needs to be called "GetTotalHours" ... but that's not what it does, it processes the week of entries. So if I was coming in fresh, I'd be confused either way. If it's called GetTotalHours, but then goes and fills in a whole timesheet, I'd definitely be thinking "what in the fuck???" ... if we call it ProcessWeek, but it returns an int, I'd be thinking "what the hell does it actually return?" and I'd need to read the code from top to bottom to determine that.`
> 
> > Having said all that, I think doing a sanity check on the total hours makes a lot of sense. I was originally going with a lamba to pass in the for-logic so it read as "Process the week of entries, and use this daily processing logic" but it was getting unnecessarily complex. I decided to use the ref so the naming stays pure, and we can track the total hours as a little ride-along. Now it reads as "Process this week you've passed in, and btw I need an int to track the total hours with." ProcessWeek(Week week, ref int totalHours)`
> 
> Would an `out` parameter be a more suitable option? E.g., `ProcessWeek(Week week, out int totalHours)` That way calling code does _not need_ to pass a ref, we get the total hours with minimal effort, and we understand the total hours as a side-effect of processing the week instead of thinking it's the purpose of the function.

It's a decent option. 

I tend to think of out parameters as "so you want to return multiple things, but you can't, eh?" So I usually see them with a method that returns something, and some out params... or, to keep it organised, have it void and return a couple of out params. It's why I very rarely use them - if you're returning multiple things it usually means you're breaking the single-responsibility rule, OR those things you returned should be grouped up in a class.

In this case, where we're accepting there is a side-effect, I like that you can instantiate the parameter in the call - something you'd usually do. It does close the door, though, on, say, processing multiple weeks and keeping a running total. We probably don't want that anyway. So it comes down to:

Is our design to preclude other options? i.e. totalHours must always start from zero at the start of every ProcessWeek?
Or, is our design to have a running total that the caller should manage because they may want to do something with that info?

Probably the former, right? So I guess `out` is best.

Good convo, btw.

**Pull request merged**
