### PR TITLE
Comments feature

### PR DESCRIPTION
**Pull request by MarkAHQ**
I immediately ran into the old ChromeDriver version problem. Even though I had chromedriver set up correctly, because this solution uses that 3rd-party ChromeDriver package.

I think we could get this going for most people - people who may not know about or what to stuff around with ChromeDriver, so I switched to a DriverManager package which should, in theory, download the correct chromdriver version as needed.

Then when I went to use it, for non-billable work (which I mostly do) you have to enter a comment. So I extended the functionality to allow for that.

In doing so, I refactored the foreach. I can see an advantage to keeping the item anonymous - as soon as I changed the record structure, it wouldn't compile forcing me to fix up the foreach loop before it would compile. But I think I should be able to extend the data structure without causing code elsewhere to fail to compile, so I changed it so that doesn't happen again.

### CODE REVIEW

**Comment by c-schembri** [comment]
Everything is good. However, if non-billable work requires a comment, shouldn't we make the program enforce a comment to be entered (by checking if it's defined in the entry in the `jobs.txt` file) before trying to save the entries on the website? On what condition comments are enforced I am not sure. (Is non-billable work simply defined by a having a 'NOCHAR' present?)

**Comment by MarkAHQ** [comment]
> 

Yeah, and that's exactly the problem I ran into. Timothy fell over in a heap because the timesheets threw an error.

However, I don't know the conditions for forcing a comment either. I know of certain timesheet codes do it (and I would bet it will be configured timesheet code to timesheet code) but probably not all of them.

So, all in all, I figured we just give people the option to enter a comment, and if they don't when they should have, the commit won't work with a big ol' error.

**Comment by c-schembri** [comment]
> I figured we just give people the option to enter a comment, and if they don't when they should have, the commit won't work with a big ol' error.

Sounds fine to me. However, will people know that such an error has even occurred? It seems to me that as soon as it happens then the program will stop executing and throw a timeout exception somewhere along the flow. Do we at least know what the comment error looks like so we can check for that during its expected appearance window? That way we can then provide a nice error message back to the user.

**Comment by MarkAHQ** [comment]
> > I figured we just give people the option to enter a comment, and if they don't when they should have, the commit won't work with a big ol' error.
> 
> Sounds fine to me. However, will people know that such an error has even occurred? It seems to me that as soon as it happens then the program will stop executing, throwing a timeout exception or similar somewhere along the flow. Do we at least know what the comment error looks like so we can check for that during its expected appearance window? That way we can then provide a nice error message back to the user (similar to how it's already done with an invalid entered username/password).

Yeah it does throw an exception - NoSuchElement - because it's trying to enter some text into a field somewhere, but the browser has moved to a different (error) window.

The problem with this approach (which comes up in testing too) is you have to frequently check for the non-existence of something ("Did that action cause an error? Wait to make sure the error screen has loaded... oh, that timed out so I guess no error screen --> Can move on now.") It's very flakey and slow. Generally, at least with a test framework, I'll just let it throw the exception.

From my perspective when I used it the first time, Timothy died, and the browser window was sitting there telling me exactly what went wrong. "This field requires a comment to commit". So I knew quickly the problem. Only downside was I had to extend the code to handle comments.

**Comment by c-schembri** [comment]
Alright, as long as the browser window stays open it's all good. I was just worried it would close and one wouldn't know exactly what happened without re-running it and watching.

**Pull request merged**
